### ISSUE TITLE
Error watching table on web

### ISSUE THREAD

**Issue by gcostaapps** [supabase-community/supabase-dart#100]
Hi, I'm running the same code on a tablet and on the web, on the web when I make changes in an array of int fields inside a table that is being watched I got an error from the realtime_client. Coudn't find why, this error was not happening before, the users start to complain about it this week.

```
_subscription = _client
            .from('liveLesson:id=eq.${r.id}')
            .on(SupabaseEventTypes.all, (payload) => watchLiveLesson(payload))
            .subscribe();
```

Error
```
Error: Expected a value of type 'String?', but got one of type '_JsonMap'
    at Object.throw_ [as throw] (http://localhost:52483/dart_sdk.js:5067:11)
    at Object.castError (http://localhost:52483/dart_sdk.js:5026:15)
    at Object.cast [as as] (http://localhost:52483/dart_sdk.js:5351:17)
    at dart.NullableType.new.as (http://localhost:52483/dart_sdk.js:6911:60)
    at realtime_subscription.Binding.new.<anonymous> (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:430:37)
    at realtime_subscription.RealtimeSubscription.new.trigger (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:521:12)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:967:145
    at WhereIterable.new.forEach (http://localhost:52483/dart_sdk.js:22295:11)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:967:117
    at realtime_client.RealtimeClient.new.<anonymous> (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:1101:81)
    at realtime_client.RealtimeClient.new.onConnMessage (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:972:12)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:831:16
    at _RootZone.runUnaryGuarded (http://localhost:52483/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:52483/dart_sdk.js:33906:22)
    at _ControllerSubscription.new.[_add] (http://localhost:52483/dart_sdk.js:33855:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36868:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36978:32)
    at _SyncStreamController.new.[_add] (http://localhost:52483/dart_sdk.js:36681:26)
    at _SyncStreamController.new.add (http://localhost:52483/dart_sdk.js:36648:19)
    at _RootZone.runUnaryGuarded (http://localhost:52483/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:52483/dart_sdk.js:33906:22)
    at _ControllerSubscription.new.[_add] (http://localhost:52483/dart_sdk.js:33855:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36868:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36978:32)
    at _SyncStreamController.new.[_add] (http://localhost:52483/dart_sdk.js:36681:26)
    at _SyncStreamController.new.add (http://localhost:52483/dart_sdk.js:36648:19)
    at _StreamSinkWrapper.new.add (http://localhost:52483/dart_sdk.js:37015:24)
    at _GuaranteeSink.new.add (http://localhost:52483/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1179:24)
    at http://localhost:52483/packages/web_socket_channel/src/copy/web_socket_impl.dart.lib.js:1470:37
    at Object._checkAndCall (http://localhost:52483/dart_sdk.js:5274:16)
    at Object.dcall (http://localhost:52483/dart_sdk.js:5279:17)
    at WebSocket.<anonymous> (http://localhost:52483/dart_sdk.js:109327:100)
```

Using flutter version stable 2.10.1 and supabase: ^0.2.15
(Was using supabase 0.2.13 before but with the same error, tried to update but the error persist)

**Comment by gcostaapps** [comment]
Hi, is there any update about this or information that I need to provide? This was not happening some weeks ago

**Comment by dshukertjr** [comment]
@gcostaapps Sorry for taking time to getting back to you and thank you so much for your patients. 

If you could provide a schema of your `liveLesson` table as well as simple code sample of what`watchLiveLesson(payload)` is doing, it would be awesome!

**Comment by gcostaapps** [comment]
Sure

I've tried to put the try catch inside the `watchLiveLesson` but when the error happens it doesn't go to the catch statement.

```
void watchLiveLesson(dynamic payload) {
    try {
      final slidesVisibleList = payload.newRecord['slidesWithVisibleAnswers'];
      List<int>? slidesVisible = [];
      if (slidesVisibleList != null) {
        final slidesVisibleListDecoded = slidesVisibleList is String
            ? json.decode(slidesVisibleList)
            : slidesVisibleList;
        if (slidesVisibleList != null) {
          for (final slideVisible in slidesVisibleListDecoded) {
            slidesVisible.add(slideVisible);
          }
        }
      }

      final slidesEditableList = payload.newRecord['slidesWithEditableAnswer'];
      List<int>? slidesEditable = [];
      if (slidesEditableList != null) {
        final slidesEditableListDecoded = slidesEditableList is String
            ? json.decode(slidesEditableList)
            : slidesEditableList;
        if (slidesEditableList != null) {
          for (final slideEditable in slidesEditableListDecoded) {
            slidesEditable.add(slideEditable);
          }
        }
      }

      emit(
        state.copyWith.call(
          liveLesson: state.liveLesson!.copyWith(
            countdownMode: payload.newRecord['countdownMode'],
            countdownSeconds: payload.newRecord['countdownSeconds'],
            countdownLastUpdate:
                payload.newRecord['countdownLastUpdate'] != null
                    ? DateTime.parse(payload.newRecord['countdownLastUpdate'])
                    : null,
            currentSlide: payload.newRecord['currentSlide'],
            isLive: payload.newRecord['isLive'],
            slideFreeControl: payload.newRecord['slideFreeControl'] ?? false,
            slidesWithVisibleAnswers: slidesVisible,
            slidesWithEditableAnswer: slidesEditable,
          ),
        ),
      );
    } catch (e) {
      print('Error watching lesson');
    }
  }
```

![image](https://user-images.githubusercontent.com/65033296/160408682-e2411b2c-8fa7-44c6-af41-cc0e64170b78.png)

The ARRAY fields are arrays of int8

**Comment by dshukertjr** [comment]
Thank you so much @gcostaapps for additional context. This is very helpful!

There is a lot going on with launch week at the moment at Supabase, but I will allocate some time at the end of the week to look into this issue along with other issues that you have kindly opened and hopefully get them fixed ASAP.
